# Generated by Django 3.0.3 on 2020-02-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='swimming_pool',
            field=models.BooleanField(default=True),
        ),
    ]
